spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/shopnow_orders
    username: postgres
    password: S@ltyGuy!1
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  application:
    name: Order Service
server:
  port: 8083

jwt:
  secret: shopnowsupersecretkey1234567890123456
  expiration: 86400000

logging:
  level:
    root: INFO
